name: Build and upload release for Chrome and Firefox

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Zip Chrome build
        run: |
          cd build
          zip -r chrome.zip chrome

      - name: Zip Firefox build
        run: |
          cd build
          zip -r firefox.zip firefox

      - name: Upload to release (tag push)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/chrome.zip
            build/firefox.zip
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest release (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        id: latest
        run: |
          latest=$(gh api repos/${{ github.repository }}/releases/latest --jq '.tag_name')
          echo "tag=$latest" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to latest release (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.latest.outputs.tag }}
          files: |
            build/chrome.zip
            build/firefox.zip
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}